### ISSUE TITLE
Trouble to get it to run

### ISSUE THREAD

**Issue by yalgoo** [frankol/ecodesign-homeassistant#3]
Hi Frank,

Thank you for your work. I have an ecodesign ED 180 RF heat pump and a waveshare 4-Ch RS485 to RJ45. Unfortunately it will not work.
I can ping the wave share from home assistant. But HA does not receive any data. 
I have doubts in my cabling.  
1) Do I need a resistance of 120 Ohm?
   a) one?
   b) two?
2) Do I need a ground wire between heat pump and waveshare?

Thank you in advance 
Christoph

**Comment by frankol** [comment]
Hi Christoph,
i dont used any resistors in my setup. Are you sure you´re using the right chanel at your waveshare adapter, since you have 4?

**Comment by yalgoo** [comment]
Thank you for your reply. It is working now. Currently I'm struggling with the PV mode. I want to start the PV mode when entity soc_battery is > 50.0%. I started with home assistant just recently. So maybe you can give me some hit.
Thanks a lot.

**Comment by herbutant** [comment]
I talked to some guys with decades of Modbus experience: In a home setting with only one Modbus device and relatively short wires termiator resistors will not be required. I used a spare Ethernet cable that I found in my cables-and-wires box and skipped the resistors. Works like a charm.

**Comment by yalgoo** [comment]
Thank you for the additional code for the automoation. It seems to work now. 
In the modbus code I did a small change to get one decimal for Ist Temperatur. So far it was integer only. 

```
sensors:
    - name: "EcoDesign WW-Temperatur Ist"
      unique_id: ecodesign_temp_ist
      address: 8
      precision: 1
      input_type: input
      unit_of_measurement: °C
      scale: 0.1
      scan_interval: 10
      slave: 3
```
