### ISSUE TITLE
Settings hard coded

### ISSUE THREAD

**Issue by herbutant** [frankol/ecodesign-homeassistant#4]
I got my instance up an running now but wanted to not have my variations (bridge-ip, port, slave_id, pollin timeout) hard coded so I made the following changes:

I added this to **secrets.yaml**

```
modbus_bridge_ip: "192.168.178.180"
modbus_bridge_port: 502
modbus_ecodesign_slave_id: 1
modbus_ecodesign_interval_sec : 30
```

In my **modbus_ecodesign.yaml**, which I include in configuration.yaml I apply these "secrets" like below
#modbus: !include modbus_ecodesign.yaml

```
- name: "wwwp"
  delay: 5
  timeout: 9
  type: tcp
  host: !secret modbus_bridge_ip
  port: !secret modbus_bridge_port
  
  climates:
    - name: "EcoDesign Solltemperatur Set"
      unique_id: ecodesign_climates_temp_soll
      scan_interval: !secret modbus_ecodesign_interval_sec
      slave: !secret modbus_ecodesign_slave_id
      #scan_interval: *settings_ecodesign.interval_sec
      #slave: *settings_ecodesign.slave_id
      address: 4
      input_type: holding
      max_temp: 62
      min_temp: 5
      precision: 1
      temp_step: 1
      target_temp_register: 4
```

As these are not really secrets I was looking at another way to include them but didn't succeed. Does anyone have a suggestion to include **settings_ecodesign.yaml** properly? so that I can refer to it (commented out variation above)?

```
settings_ecodesign: &settings_ecodesign
  slave_id: 1
  interval_sec : 30
```
