### ISSUE TITLE
Skalierungsfehler "Ist-temperatur" bei der Identität  "Solltemperatur Set" in der Thermostat Karte

### ISSUE THREAD

**Issue by Pirol9** [frankol/ecodesign-homeassistant#8]
Bei der Anzeige der Identität "EcoDesign Solltemperatur Set", wird die Ist-Temperatur x10 angezeigt (anstatt 42,3 wird 432 angezeigt).

Wo kann man dies einstellen?

![Image](https://github.com/user-attachments/assets/75db154c-6f1d-4c1e-a948-3cf0f787566b)
![Image](https://github.com/user-attachments/assets/26c05e45-2716-4012-80e0-65cbdbb2f7cc)

Danke für die Unterstützung und die hervorragende Arbeit!👍

**Comment by Pirol9** [comment]
Dies hatte ich auch schon probiert. Danach passt die Ist-Temperatur. Nur die Soll-Temperatur stimmt nicht mehr. Stand vorher z.B. auf 48°C, nach der Änderung stehen da 5°C im Thermostat. Ändere ich den Sollwert bleibt er auf 4,8 stehen.

Rein aus Interesse. Im Handbuch steht für Modbus Adresse **8** -> "009.Start_HP_Hour" und bei Adresse **4** -->"005.T_setpoint"

![Image](https://github.com/user-attachments/assets/7cfb2ad6-2ffd-41d7-93e0-af589c56f40a)

![Image](https://github.com/user-attachments/assets/605d44cc-cd03-443a-b27c-238f5d0ff530)

**Comment by frankol** [comment]
> Rein aus Interesse. Im Handbuch steht für Modbus Adresse 8 -> "009.Start_HP_Hour" und bei Adresse 4 -->"005.T_setpoint"

Wahrscheinlich ist in Adresse 8 bei der ED100 richtig. Lass die Adresse 4 und bei Type holding drin stehen. Ich habe es aktuell in der modbus.yaml angepasst

**Comment by frankol** [comment]
ich sehe gerade, dass ja die IST-Temp ja irgendwo herkommen muss.  Das ist tatsächlich auf der Adresse 8 zu finden

```
 sensors:
    - name: "EcoDesign WW-Temperatur Ist"
      unique_id: ecodesign_temp_ist
      address: 8
      data_type: int16
      input_type: input
      unit_of_measurement: °C
      scale: 0.1
      scan_interval: 10
      slave: 3
```

Das Problem ist, dass Temp-IST ein INPUT Register ist und Temp-Set ein holding Register. HA kann das aktuell nicht umsetzen, daher bleib bei Register 4 für IST und SET
